"""
AI Self-Training & Continuous Active Learning Package for Project Garuda.
"""

from ai_engine.learning.active_learner import ActiveLearningHarvester, HarvestedSample, TriggerType, SampleLabel
from ai_engine.learning.self_trainer import SelfTrainingEngine, ModelCheckpoint
from ai_engine.learning.adaptive_filter import AdaptiveNegativeFilter, NegativeExemplar, SpatialBayesianPrior
from ai_engine.learning.data_foundation import (
    LearningSample,
    CameraProfile,
    LearningEvent,
    DatasetVersion,
    ModelVersion,
    FeedbackRecord,
    ValidationStatus,
    SelectionReason,
    LearningEventType,
)
from ai_engine.learning.memory_manager import LearningMemoryManager, memory_manager
from ai_engine.learning.confidence_calibrator import (
    compute_entropy,
    compute_class_margin,
    compute_bbox_stability,
    detect_confidence_drop,
    CameraCalibrator,
    SampleSelectionPolicy,
)
from ai_engine.learning.camera_environment_adapter import (
    CameraEnvironmentAdapter,
    LightingProfile,
    SceneBaseline,
    MovementPatterns,
    DetectionStatistics,
    AdaptiveParameters,
)
from ai_engine.learning.self_supervised_learner import (
    SceneRepresentationExtractor,
    CircadianTemporalBaseline,
    MovementManifold,
    AppearanceManifoldCluster,
    SelfSupervisedEnvironmentLearner,
)
from ai_engine.learning.anomaly_novelty_engine import (
    AnomalySeverityTier,
    AnomalyAssessment,
    NovelObjectDetector,
    TrajectoryAnomalyDetector,
    TemporalAnomalyDetector,
    SceneActivityAnomalyDetector,
    AnomalyNoveltyEngine,
    get_anomaly_engine,
)
from ai_engine.learning.continual_learner import (
    ReplayExemplar,
    GoldenReplayBuffer,
    StratifiedBatchSampler,
    DistillationLossRegularizer,
    RegressionBenchmarkEvaluator,
    RegressionEvaluationReport,
    BenchmarkClassScore,
    ContinualLearner,
    continual_learner,
)
from ai_engine.learning.synthetic_augmentor import (
    CCTVDegradationSynthesizer,
    AugmentedSampleVariation,
    TargetedAugmentationPolicy,
    DataDiversityEvaluator,
    synthetic_augmentor,
)
from ai_engine.learning.shadow_deployment import (
    DeploymentStage,
    ShadowComparisonMetric,
    DeploymentStatusReport,
    SafetyRollbackGuard,
    ShadowInferenceEngine,
    AtomicModelHotSwapper,
    SafeDeploymentManager,
    deployment_manager,
)
from ai_engine.learning.federated_sync import (
    FederatedRepresentationPayload,
    DifferentialPrivacySanitizer,
    FederatedClusterSynchronizer,
    FederatedPriorAggregator,
    federated_synchronizer,
)

from ai_engine.learning.orchestrator import (
    LearningLifecycleState,
    DecisionFactor,
    DecisionAttribution,
    DecisionAttributionEngine,
    LineageNode,
    LineageGraphTracker,
    CentralLearningOrchestrator,
    get_learning_orchestrator,
)

from ai_engine.learning.production_hardening import (
    CircuitBreakerState,
    CircuitBreakerOpenException,
    CircuitBreakerMetrics,
    CircuitBreaker,
    EvictionPolicy,
    QueueItem,
    BoundedEvictionQueue,
    FailureLogEntry,
    AsyncFailureIsolator,
    LRUCache,
    MemoryBoundsManager,
)

__all__ = [
    "ActiveLearningHarvester",
    "HarvestedSample",
    "TriggerType",
    "SampleLabel",
    "SelfTrainingEngine",
    "ModelCheckpoint",
    "AdaptiveNegativeFilter",
    "NegativeExemplar",
    "SpatialBayesianPrior",
    "LearningSample",
    "CameraProfile",
    "LearningEvent",
    "DatasetVersion",
    "ModelVersion",
    "FeedbackRecord",
    "ValidationStatus",
    "SelectionReason",
    "LearningEventType",
    "LearningMemoryManager",
    "memory_manager",
    "compute_entropy",
    "compute_class_margin",
    "compute_bbox_stability",
    "detect_confidence_drop",
    "CameraCalibrator",
    "SampleSelectionPolicy",
    "CameraEnvironmentAdapter",
    "LightingProfile",
    "SceneBaseline",
    "MovementPatterns",
    "DetectionStatistics",
    "AdaptiveParameters",
    "SceneRepresentationExtractor",
    "CircadianTemporalBaseline",
    "MovementManifold",
    "AppearanceManifoldCluster",
    "SelfSupervisedEnvironmentLearner",
    "AnomalySeverityTier",
    "AnomalyAssessment",
    "NovelObjectDetector",
    "TrajectoryAnomalyDetector",
    "TemporalAnomalyDetector",
    "SceneActivityAnomalyDetector",
    "AnomalyNoveltyEngine",
    "get_anomaly_engine",
    "ReplayExemplar",
    "GoldenReplayBuffer",
    "StratifiedBatchSampler",
    "DistillationLossRegularizer",
    "RegressionBenchmarkEvaluator",
    "RegressionEvaluationReport",
    "BenchmarkClassScore",
    "ContinualLearner",
    "continual_learner",
    "CCTVDegradationSynthesizer",
    "AugmentedSampleVariation",
    "TargetedAugmentationPolicy",
    "DataDiversityEvaluator",
    "synthetic_augmentor",
    "DeploymentStage",
    "ShadowComparisonMetric",
    "DeploymentStatusReport",
    "SafetyRollbackGuard",
    "ShadowInferenceEngine",
    "AtomicModelHotSwapper",
    "SafeDeploymentManager",
    "deployment_manager",
    "FederatedRepresentationPayload",
    "DifferentialPrivacySanitizer",
    "FederatedClusterSynchronizer",
    "FederatedPriorAggregator",
    "federated_synchronizer",
    "LearningLifecycleState",
    "DecisionFactor",
    "DecisionAttribution",
    "DecisionAttributionEngine",
    "LineageNode",
    "LineageGraphTracker",
    "CentralLearningOrchestrator",
    "get_learning_orchestrator",
    "CircuitBreakerState",
    "CircuitBreakerOpenException",
    "CircuitBreakerMetrics",
    "CircuitBreaker",
    "EvictionPolicy",
    "QueueItem",
    "BoundedEvictionQueue",
    "FailureLogEntry",
    "AsyncFailureIsolator",
    "LRUCache",
    "MemoryBoundsManager",
]


